### ISSUE TITLE
[BUG] SillyTavern install bitsadmin error

### ISSUE THREAD

**Issue by Arztpla** [deffcolony/ai-toolbox#2]
**Describe the bug**
Running the SillyTavern install script

The vs_buildtools were not present in my %temp% folder
Line 283-284 in st-install.bat

![280410239-9ab6e657-3393-44c2-9063-8ec453f55e7d](https://github.com/deffcolony/ai-toolbox/assets/145367153/190ac61e-88c1-40cc-a0af-bd3dc49555c6)

**Comment by deffcolony** [comment]
@Arztpla I Fixed the bug. You can do **git pull** or download the zip again

Commit update: https://github.com/deffcolony/ai-toolbox/commit/06fcd103e73676262ef53f44ab221f476964d5d5
